### PR TITLE
[Magento 2.4.6 installs broken] Replacing Zend dependency with Laminas

### PR DESCRIPTION
**Pull request by sol-loup**
# Issues installing Auctane/API via composer. 

On Magento 2.4.6, setup:di:compile after installing via Composer returns Class "Zend\Http\Client" does not exist. This is due to a well-known deprecation of the Zend libraries in favor of Laminas. Until this is mitigated, sellers on the newest supported version of Magento cannot safely install shipstation via composer. 

This PR swaps the underlying client in-place. This should be safe, as the Client interface is common between both libraries.

### CODE REVIEW

**Comment by sol-loup** [comment]
@quangdog @ricky when you get the chance

**Comment by CalzaFino** [comment]
On previously installed Auctane I just installed some Laminas updates and it broke Compilation on Magento 2.4.6-p3
I get this error:

In ClassReader.php line 57:
  Impossible to process constructor argument Parameter #15 [ <required> Zend\Http\Client $zendClient ] of Auctane\Api\Model\Carrier\Shipping class
In GetParameterClassTrait.php line 34:
  Class "Zend\Http\Client" does not exist

Not sure what the effect will be on the live site. please review this ASAP.

**Comment by shubhsheth** [comment]
I am getting an error during checkout because of this. This is affecting users from completing the checkout process on the site.

**Comment by CalzaFino** [comment]
I tried the changed file Shipping.php but I am getting the Error: Undefined variable $laminasClient in /cache/vendor/auctane/api/Model/Carrier/Shipping.php on line 130

**Comment by shubhsheth** [comment]
@CalzaFino I don't see `$laminasClient` in suggested changes. I'd recommend replacing your Shipping.php with this file - https://raw.githubusercontent.com/shipstation/plugin-magento/c2573bd3a14935db9caa8ac9a2cae173ddc6bcd1/Api/Model/Carrier/Shipping.php

**Comment by ricky** [comment]
Incorporated into #43

**Pull request closed without merging**
